[[ROCmCompilerSupport]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfa811018f95cdab2fa90512eee59c0fc9d1c728"
libc = "glibc"
os = "linux"

    [[ROCmCompilerSupport.download]]
    sha256 = "48ed26fd279a5f1eeb7ba3fa62fa8659c99f9cd93f38fc9d3719b15271b2e2c1"
    url = "https://github.com/JuliaBinaryWrappers/ROCmCompilerSupport_jll.jl/releases/download/ROCmCompilerSupport-v4.2.0+1/ROCmCompilerSupport.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmCompilerSupport]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfb4e06bdad9ca5d94eaeffa2ed93fb12718d87d"
libc = "musl"
os = "linux"

    [[ROCmCompilerSupport.download]]
    sha256 = "03a8b87e133a1f47b0e4e54c66a1d0c7c8aebc3597ece8fa89cfde18877396e9"
    url = "https://github.com/JuliaBinaryWrappers/ROCmCompilerSupport_jll.jl/releases/download/ROCmCompilerSupport-v4.2.0+1/ROCmCompilerSupport.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
