[[ROCmCompilerSupport]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b136fcfe77aceea851a618f1e0b87aa12ab344c1"
libc = "glibc"
os = "linux"

    [[ROCmCompilerSupport.download]]
    sha256 = "8b6832d83a310d4c391fe256626f0f06d5f5f46327cf4af4865c9472b4402c12"
    url = "https://github.com/JuliaBinaryWrappers/ROCmCompilerSupport_jll.jl/releases/download/ROCmCompilerSupport-v4.0.0+0/ROCmCompilerSupport.v4.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmCompilerSupport]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2bab2b0e5345b2c51d799ab69140ca975f5f1c8"
libc = "musl"
os = "linux"

    [[ROCmCompilerSupport.download]]
    sha256 = "ef2e30face7f6d6c0cdc70b3780b3a156d4ee517cc07c92e84cbd2d8f6102b5a"
    url = "https://github.com/JuliaBinaryWrappers/ROCmCompilerSupport_jll.jl/releases/download/ROCmCompilerSupport-v4.0.0+0/ROCmCompilerSupport.v4.0.0.x86_64-linux-musl-cxx11.tar.gz"
