[[ROCmCompilerSupport]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc3573bd1269871f02234cd0cd6fbe70117b090a"
libc = "glibc"
os = "linux"

    [[ROCmCompilerSupport.download]]
    sha256 = "5de1bf5d4209280a3ea2e7083629c17cd2ae8a42421879687bb55a852aa3a92f"
    url = "https://github.com/JuliaBinaryWrappers/ROCmCompilerSupport_jll.jl/releases/download/ROCmCompilerSupport-v5.2.3+0/ROCmCompilerSupport.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmCompilerSupport]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08ca6f9495ba9bb796fb45288529fc98d5dfaa79"
libc = "musl"
os = "linux"

    [[ROCmCompilerSupport.download]]
    sha256 = "81a3b0e186ffa099162a5622a65a721e2a0625f08ed45796081fd1809f47fe56"
    url = "https://github.com/JuliaBinaryWrappers/ROCmCompilerSupport_jll.jl/releases/download/ROCmCompilerSupport-v5.2.3+0/ROCmCompilerSupport.v5.2.3.x86_64-linux-musl-cxx11.tar.gz"
