[[ROCmCompilerSupport]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20a1b284246402d08a62b6852076a9aeb04380cb"
libc = "glibc"
os = "linux"

    [[ROCmCompilerSupport.download]]
    sha256 = "e86a507bef66ebd8b5c8b981f832886d9398917f965216e8a71d654965c22240"
    url = "https://github.com/JuliaBinaryWrappers/ROCmCompilerSupport_jll.jl/releases/download/ROCmCompilerSupport-v5.4.4+0/ROCmCompilerSupport.v5.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmCompilerSupport]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8c7af1fe1d3175731d98bb70f5755a9c11d831e"
libc = "musl"
os = "linux"

    [[ROCmCompilerSupport.download]]
    sha256 = "02b8a40c2caf2dc7cc5b594f3e8873b664aacc210c3308eb2c1e4ac5203f68a1"
    url = "https://github.com/JuliaBinaryWrappers/ROCmCompilerSupport_jll.jl/releases/download/ROCmCompilerSupport-v5.4.4+0/ROCmCompilerSupport.v5.4.4.x86_64-linux-musl-cxx11.tar.gz"
